
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const generateTripPDF = async (budgetData: any, tripDetails: any) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  // Header
  pdf.setFontSize(20);
  pdf.setTextColor(41, 128, 185);
  pdf.text('Solo Travel Budget Plan', pageWidth / 2, 25, { align: 'center' });
  
  // Trip Details
  pdf.setFontSize(14);
  pdf.setTextColor(0, 0, 0);
  pdf.text('Trip Details', 20, 50);
  
  pdf.setFontSize(11);
  pdf.text(`Destination: ${tripDetails.toLocation}`, 20, 65);
  pdf.text(`From: ${tripDetails.fromLocation}`, 20, 75);
  pdf.text(`Duration: ${tripDetails.duration} days`, 20, 85);
  pdf.text(`Travel Date: ${new Date(tripDetails.travelDate).toLocaleDateString()}`, 20, 95);
  pdf.text(`Transport: ${tripDetails.transport}`, 20, 105);
  pdf.text(`Stay: ${tripDetails.stay}`, 20, 115);
  
  // Budget Breakdown
  pdf.setFontSize(14);
  pdf.text('Budget Breakdown', 20, 140);
  
  pdf.setFontSize(11);
  let yPos = 155;
  
  const breakdown = budgetData.breakdown;
  pdf.text(`Transport: ₹${breakdown.transport.toLocaleString()}`, 20, yPos);
  pdf.text(`Stay: ₹${breakdown.stay.toLocaleString()}`, 20, yPos + 10);
  pdf.text(`Food: ₹${breakdown.food.toLocaleString()}`, 20, yPos + 20);
  pdf.text(`Activities: ₹${breakdown.activities.toLocaleString()}`, 20, yPos + 30);
  pdf.text(`Miscellaneous: ₹${breakdown.miscellaneous.toLocaleString()}`, 20, yPos + 40);
  
  // Total
  pdf.setFontSize(14);
  pdf.setTextColor(220, 53, 69);
  pdf.text(`Total Budget: ₹${breakdown.total.toLocaleString()}`, 20, yPos + 60);
  
  // AI Suggestions
  pdf.setFontSize(14);
  pdf.setTextColor(0, 0, 0);
  pdf.text('AI Travel Tips', 20, yPos + 85);
  
  pdf.setFontSize(10);
  budgetData.suggestions.forEach((suggestion: string, index: number) => {
    const lines = pdf.splitTextToSize(suggestion, pageWidth - 40);
    pdf.text(lines, 20, yPos + 100 + (index * 15));
  });
  
  // Money Saving Tips
  pdf.setFontSize(14);
  pdf.text('Money Saving Tips', 20, yPos + 160);
  
  pdf.setFontSize(10);
  budgetData.savings.forEach((saving: string, index: number) => {
    const lines = pdf.splitTextToSize(saving, pageWidth - 40);
    pdf.text(lines, 20, yPos + 175 + (index * 15));
  });
  
  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text('Generated by Solo Travel Budget Estimator', pageWidth / 2, pageHeight - 10, { align: 'center' });
  
  // Save the PDF
  pdf.save(`${tripDetails.toLocation}_Travel_Budget.pdf`);
};
